# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sandro's homepage
masthead_title: SANDRO SPETH'S HOMEPAGE
email: sandro.speth@iste.uni-stuttgart.de
description: >- # this means to ignore newlines until "baseurl:"
  This is a test homepage for GitHub Pages. It is used to play around with GitHub pages to build an academic homepage for CV and publications.
twitter_username: spethso
github_username: spethso
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/Berlin" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

breadcrumbs: true  # disabled by default

twitter:
  username: "spethso"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives

author:
  name   : "Sandro Speth"
  avatar : "/assets/images/Speth.png"
  bio    :  "Research assistant and PhD student at the University of Stuttgart, Gold Microsoft Learn Student Ambassador, and co-founder of the Microsoft Campus Community and leader of its Baden-Württemberg Hub."
  location: "Stuttgart, Germany"
  links:
    - label: "E-Mail"
      icon: "fas fa-envelope-square"
      url: "mailto:sandro.speth@iste.uni-stuttgart.de"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/spethso"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sandro-speth/?locale=en_US"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/spethso"
    - label: "YouTube"
      icon: "fab fa-youtube-square"
      url: "https://www.youtube.com/c/SandroSpeth"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com/citations?user=Tyz30W4AAAAJ&hl=de&oi=ao"
    - label: "University Page"
      icon: "fas fa-fw fa-link"
      url: "https://www.iste.uni-stuttgart.de/de/institut/team/Speth-00002/"
    - label: "MLSA"
      icon: "fas fa-fw fa-link"
      url: "https://studentambassadors.microsoft.com/en-US/profile/218"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/spethso"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sandro-speth/?locale=en_US"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/spethso"
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/c/SandroSpeth"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
      permalink: "/posts/"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
      permalink: "/"
    values:
      layout: single
      author_profile: true

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
